"""empty message

Revision ID: 27a0ed2a49d0
Revises: d1bccf37090a
Create Date: 2020-05-23 15:37:35.574465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a0ed2a49d0'
down_revision = 'd1bccf37090a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todosnew', sa.Column('list_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todosnew', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todosnew', type_='foreignkey')
    op.drop_column('todosnew', 'list_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
