"""empty message

Revision ID: d1bccf37090a
Revises: b5be3382e818
Create Date: 2020-05-21 16:00:40.203057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1bccf37090a'
down_revision = 'b5be3382e818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todosnew', sa.Column('completed', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todosnew', 'completed')
    # ### end Alembic commands ###
